[package]
name = "aoc-lib"
version = "0.1.0"
edition = "2021"
authors = ["josedanielgrayson@gmail.com"]

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
dotenv = "0.15.0"
chrono = "0.4.23"
num = "0.4.0"
colored = "2.0.0"
ansi-escapes = "0.1.1"
